// <auto-generated />
using ClickBait.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickBait.Infra.Data.Migrations
{
    [DbContext(typeof(ClickBaitContext))]
    [Migration("20220423132609_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClickBait.Infra.Entities.ClickCount", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("Varchar(36)");

                    b.Property<long>("Qtd")
                        .HasColumnType("BIGINT");

                    b.HasKey("PostId");

                    b.ToTable("ClicksCounts");
                });

            modelBuilder.Entity("ClickBait.Infra.Entities.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Varchar(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "178c25b0-c01d-4e37-8a00-81f61022777a",
                            Description = "Dignissimos qui culpa dolorum perspiciatis laborum fugiat ut qui voluptate ut voluptatem dolorem perspiciatis et debitis non facilis eos at.",
                            Title = "Est qui aperiam."
                        },
                        new
                        {
                            Id = "cc5eabc9-513e-4a8a-86ce-df794673317b",
                            Description = "Est quam aut voluptatem qui commodi consectetur consequatur est velit quia ut pariatur sed officia sed voluptatem dolorem eaque provident.",
                            Title = "Repellendus numquam dolorem."
                        },
                        new
                        {
                            Id = "9d4d64c6-8ae9-4950-b935-5577db3e4e87",
                            Description = "Incidunt praesentium accusantium aliquam fugit soluta nisi repellat repudiandae nam veritatis voluptate est et eligendi harum eligendi voluptas est maiores.",
                            Title = "Aut nisi qui."
                        },
                        new
                        {
                            Id = "c0c424c3-dfe8-4953-b025-7ba936c9bd49",
                            Description = "Et labore quis dolor in architecto nobis ut odit id delectus voluptas tenetur accusamus voluptas id accusantium commodi enim quis.",
                            Title = "Voluptatum tempore quidem."
                        },
                        new
                        {
                            Id = "33a2c323-54bc-4c74-8651-66f0cfd3f006",
                            Description = "Accusamus nobis est optio quaerat sapiente consequatur vel voluptas quidem sed quasi accusantium possimus tenetur odio ipsum pariatur ducimus incidunt.",
                            Title = "Maxime explicabo earum."
                        },
                        new
                        {
                            Id = "93b1b57f-fea6-481a-8802-9d55a0eb351b",
                            Description = "Dolorem natus maiores incidunt facere distinctio veniam sunt quod et dolorum aut autem laboriosam debitis quae vel voluptatum non quis.",
                            Title = "Asperiores ad et."
                        },
                        new
                        {
                            Id = "b2660579-a3b8-4ae2-be7c-c16154ba4256",
                            Description = "Quisquam aut possimus voluptatibus quia at ea aperiam et id deleniti similique autem sit voluptas ex quidem facilis et vel.",
                            Title = "Consequuntur magni enim."
                        },
                        new
                        {
                            Id = "e9d1d8e1-3691-40c4-95ee-79afc3db7e70",
                            Description = "Ea eos odit est magni modi est dolorem numquam fugit exercitationem quo quo qui illo dignissimos fugiat quo aliquid non.",
                            Title = "Non recusandae ut."
                        },
                        new
                        {
                            Id = "a72fdf55-0a58-426d-b7c6-f092f765d8ad",
                            Description = "Quod ut totam ea fuga accusamus sed eos sapiente corrupti optio necessitatibus aut quia doloribus at et eos accusantium tenetur.",
                            Title = "Culpa quas est."
                        },
                        new
                        {
                            Id = "a2504a1c-2724-4b8e-9aa7-a71341626d2c",
                            Description = "Sit aperiam blanditiis magnam sunt delectus dolorem aliquam a soluta amet cumque ad et dolores necessitatibus qui quasi aut sunt.",
                            Title = "Rem occaecati inventore."
                        });
                });

            modelBuilder.Entity("ClickBait.Infra.Entities.ClickCount", b =>
                {
                    b.HasOne("ClickBait.Infra.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
